# this configuration file has all empty custom components set up.
# use 'esphome test_empty.yaml compile' to build. 

packages:
  device: !include device.yaml # include our test device setup

sensor:
  - platform: empty_sensor
    name: Empty sensor

  - platform: empty_i2c_sensor
    name: Empty I2C sensor

  - platform: empty_spi_sensor
    name: Empty SPI sensor
    cs_pin: D8

  - platform: empty_uart_sensor
    name: Empty UART sensor

  - platform: empty_compound_sensor
    sensor1:
      name: Sensor 1
    sensor2:
      name: Sensor 2
    sensor3:
      name: Sensor 3  

binary_sensor:
  - platform: empty_binary_sensor
    name: Empty binary sensor
  
output:
  - platform: empty_binary_output
    id: empty_binary_output_1

  - platform: empty_float_output
    id: empty_float_output_1

light:
  - platform: empty_light
    name: Empty light
    output: empty_float_output_1
    
switch:
  - platform: empty_switch
    name: Empty switch

fan:
  - platform: empty_fan
    name: Empty fan
    output: empty_binary_output_1

text_sensor:
  - platform: empty_text_sensor
    name: Empty text sensor

cover:
  platform: empty_cover
  name: Empty cover

empty_component:
  id: empty_component_1

i2c:
  sda: 4
  scl: 5

empty_i2c_component:
  id: empty_i2c_component_1
  address: 0x01

uart:
  tx_pin: D0
  rx_pin: D1
  baud_rate: 9600

empty_uart_component:
  id: empty_uart_component_1

spi:
  clk_pin: D5
  miso_pin: D6

empty_spi_component:
  id: empty_spi_component_1
  cs_pin: D8